name: Lint and Tests

on:
  push:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Install Playwright browsers
      run: |
        uv run playwright install chromium

    - name: Lint with ruff
      run: |
        uv run ruff check .
        uv run ruff format --check .

    - name: Run tests
      run: |
        uv run pytest -v --tb=short

    - name: Run tests with parallel execution
      run: |
        uv run pytest -n auto --tb=short

  frontend-tests:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Install Playwright browsers
      run: |
        uv run playwright install chromium --with-deps

    - name: Run frontend tests only
      run: |
        uv run pytest align_browser/test_frontend.py -v

    - name: Run real data tests (if available)
      run: |
        uv run pytest align_browser/test_frontend_real_data.py -v
      continue-on-error: true  # Real data might not be available in CI

    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-screenshots
        path: /tmp/*.png
        retention-days: 7

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Test build script
      run: |
        # Test the build script works
        uv run pytest align_browser/test_build.py -v

    - name: Build package
      run: |
        uv build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package
        path: dist/
        retention-days: 7